sites:
  angle:
    url: https://angle.lecointreparis.com
    name: Angle
  kosmo:
    url: https://kosmo.lecointreparis.com
    name: Kosmo
  19m:
    url: https://19m.lecointreparis.com
    name: 19M
